{
 "title": "Monitoring and Logs Dashboard",
 "tags": [
  "Logging",
  "Monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Transaction Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  CONCAT(\r\n    '[', \r\n    CASE \r\n      WHEN message ILIKE '%success%' THEN 'INFO' \r\n      ELSE 'ERROR' \r\n    END, \r\n    '] ',\r\n    'user=', tl.metadata->>'username', ' ',\r\n    'action=', tl.metadata->>'actionType', ' ',\r\n    'url=', tl.metadata->>'url', ' ',\r\n    'message=\"', message, '\"'\r\n  ) AS message,\r\n  CASE \r\n    WHEN message ILIKE '%success%' THEN 'INFO' \r\n    ELSE 'ERROR' \r\n  END AS level,\r\n  tl.metadata->>'username' AS username,\r\n  rs_id,\r\n  tl.metadata->>'actionType' AS action_type,\r\n  tl.metadata->>'url' AS url,\r\n  message AS description\r\nFROM transaction_logs tl\r\nWHERE\r\n  $__timeFilter(time) \r\nORDER BY time DESC;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Active Users",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  tl.metadata->>'username' AS username,\r\n  count(*) AS \"total_transactions\"\r\nFROM\r\n  transaction_logs tl\r\nWHERE\r\n  tl.metadata->>'username' IS NOT NULL\r\n  AND $__timeFilter(time) \r\nGROUP BY\r\n  username\r\nORDER BY\r\n  \"total_transactions\" DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Requisition Updates Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 hour', updated_at) as time, COUNT(*) as \"Updates\" FROM requisitions WHERE updated_at >= NOW() - INTERVAL '24 hours' GROUP BY time_bucket('1 hour', updated_at) ORDER BY time;"
    }
   ]
  },
  {
   "title": "Transaction Volume by Journey Level",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('24 hour', \"time\") AS \"time\",\r\n  level,\r\n  count(*) AS \"count\"\r\nFROM\r\n  transaction_logs\r\nWHERE\r\n  $__timeFilter(\"time\")\r\nGROUP BY\r\n  1, 2\r\nORDER BY\r\n  1, 2;"
    }
   ]
  },
  { "title": "KPI Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total Requests (24h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 hour', time) as time, COUNT(*) as \"Requests\" FROM transaction_logs WHERE time >= NOW() - INTERVAL '24 hours' GROUP BY time_bucket('1 hour', time) ORDER BY time;"
    }
   ]
  },
  {
   "title": "System CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|veth.|docker.\"}[5m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|veth.|docker.\"}[5m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Host System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) * 100",
     "legendFormat": "Active Time"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "Idle Time"
    }
   ]
  },
  {
   "title": "Memory Usage Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "bargauge",
   "description": "Volumes\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  (\r\n    1 - (\r\n      node_filesystem_avail_bytes{fstype=~\"ext4|xfs\", mountpoint!~\"/mnt/wsl.*|.*docker/overlay2.*\"}\r\n      /\r\n      node_filesystem_size_bytes{fstype=~\"ext4|xfs\", mountpoint!~\"/mnt/wsl.*|.*docker/overlay2.*\"}\r\n    )\r\n  ) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}