apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    database: prs_local
    user: prs_user
    secureJsonData:
      password: localdev123
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
    isDefault: false
    editable: true
